# Generated by Django 5.1.4 on 2024-12-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questions",
            "0002_alter_explanationstep_options_alter_option_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=6,
                null=True,
            ),
        ),
    ]
