# Generated by Django 5.1.4 on 2024-12-31 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_difficulty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("created_at",)},
        ),
    ]
